# Generated by Django 4.0.4 on 2022-05-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pratos',
            old_name='tempo_mdeio_preparo',
            new_name='tempo_medio_preparo',
        ),
    ]
