# Generated by Django 4.0.4 on 2022-06-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0002_prato_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
