# Generated by Django 4.0.4 on 2022-06-08 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0003_prato_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 15, 0, 50, 616395)),
        ),
    ]
