# Generated by Django 4.0.4 on 2022-06-08 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0004_prato_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 15, 5, 43, 105518)),
        ),
    ]
