# Generated by Django 4.0.4 on 2022-06-09 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0005_rename_foto_receita_prato_foto_prato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 8, 54, 52, 744589)),
        ),
    ]
