# Generated by Django 4.0.4 on 2022-06-09 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0005_alter_prato_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 7, 39, 31, 298316)),
        ),
    ]
