# Generated by Django 4.0.4 on 2022-07-18 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pratos', '0006_alter_prato_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 8, 33, 35, 264062)),
        ),
        migrations.AlterField(
            model_name='prato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
