# Generated by Django 4.0.4 on 2022-11-21 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0009_prato_pessoa_alter_prato_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 11, 7, 47, 7665)),
        ),
    ]
