# Generated by Django 4.0.4 on 2022-06-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoa_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
