# Generated by Django 4.0.4 on 2022-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(max_length=70)),
                ('principal', models.CharField(max_length=50)),
                ('acompanhamento', models.TextField()),
                ('tempo_medio_preparo', models.IntegerField()),
                ('serve_ate', models.CharField(max_length=70)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
