# Generated by Django 4.0.4 on 2022-06-09 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0003_prato_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 8, 10, 44, 490141)),
        ),
        migrations.AddField(
            model_name='prato',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
