# Generated by Django 4.0.4 on 2022-11-21 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0006_alter_prato_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 11, 3, 34, 997165)),
        ),
        migrations.AlterField(
            model_name='prato',
            name='foto_prato',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
